// shared/src/enums/auth.enums.ts

/**
 * Authentication error codes
 */
export enum AuthErrorCode {
  INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  INSUFFICIENT_ROLE = 'AUTH_INSUFFICIENT_ROLE',
  INSUFFICIENT_TYPE = 'AUTH_INSUFFICIENT_TYPE',
  USER_DELETED = 'AUTH_USER_DELETED',
  SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  VALIDATION_ERROR = 'AUTH_VALIDATION_ERROR',
  SERVICE_UNAVAILABLE = 'AUTH_SERVICE_UNAVAILABLE',
}
