// shared/src/enums/merchant.enums.ts

/**
 * Merchant Error Codes
 */
export enum MerchantErrorCode {
  // General errors
  MERCHANT_NOT_FOUND = 'MERCHANT_NOT_FOUND',
  INVALID_MERCHANT_ID = 'INVALID_MERCHANT_ID',

  // Sync errors
  SYNC_ALREADY_RUNNING = 'SYNC_ALREADY_RUNNING',
  NO_NEW_PRODUCTS = 'NO_NEW_PRODUCTS',
  SYNC_FAILED = 'SYNC_FAILED',

  // Update errors
  UPDATE_FAILED = 'UPDATE_FAILED',
  INVALID_STATUS = 'INVALID_STATUS',
}

/**
 * Group Error Codes
 */
export enum GroupErrorCode {
  // General errors
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  INVALID_GROUP_ID = 'INVALID_GROUP_ID',

  // Create/Update errors
  GROUP_NAME_EXISTS = 'GROUP_NAME_EXISTS',
  INVALID_SOURCE_MERCHANT = 'INVALID_SOURCE_MERCHANT',
  CREATE_FAILED = 'CREATE_FAILED',
  UPDATE_FAILED = 'UPDATE_FAILED',

  // Member errors
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS',
  CANNOT_REMOVE_SOURCE = 'CANNOT_REMOVE_SOURCE',

  // Operation errors
  SYNC_ALREADY_RUNNING = 'SYNC_ALREADY_RUNNING',
  NO_MEMBERS_TO_PROCESS = 'NO_MEMBERS_TO_PROCESS',
  APPLY_TEMPLATE_FAILED = 'APPLY_TEMPLATE_FAILED',

  // Delete errors
  DELETE_FAILED = 'DELETE_FAILED',
  GROUP_HAS_MEMBERS = 'GROUP_HAS_MEMBERS',
}
