// shared/src/enums/merchant.enums.ts

/**
 * Merchant Error Codes
 */
export enum MerchantErrorCode {
  // Fetch operations
  GET_AVAILABLE_MERCHANTS_ERROR = 'GET_AVAILABLE_MERCHANTS_ERROR',
  GET_REGISTERED_MERCHANTS_ERROR = 'GET_REGISTERED_MERCHANTS_ERROR',
  FETCH_ERROR = 'FETCH_ERROR',

  // Registration operations
  ADD_MERCHANTS_ERROR = 'ADD_MERCHANTS_ERROR',
  ALREADY_REGISTERED = 'ALREADY_REGISTERED',
  REGISTRATION_ERROR = 'REGISTRATION_ERROR',

  // Update operations
  UPDATE_MERCHANT_ERROR = 'UPDATE_MERCHANT_ERROR',
  UPDATE_ERROR = 'UPDATE_ERROR',

  // Removal operations
  REMOVE_MERCHANT_ERROR = 'REMOVE_MERCHANT_ERROR',
  REMOVAL_ERROR = 'REMOVAL_ERROR',

  // General validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MERCHANT_NOT_FOUND = 'MERCHANT_NOT_FOUND',
  INVALID_MERCHANT_ID = 'INVALID_MERCHANT_ID',
  INVALID_REGISTRY_ID = 'INVALID_REGISTRY_ID',

  // Business logic errors
  MERCHANT_VALIDATION_FAILED = 'MERCHANT_VALIDATION_FAILED',
  BULK_OPERATION_PARTIAL_FAILURE = 'BULK_OPERATION_PARTIAL_FAILURE',
}

/**
 * Group Error Codes
 */
export enum GroupErrorCode {
  // Fetch operations
  GET_GROUPS_ERROR = 'GET_GROUPS_ERROR',
  GET_GROUP_DETAILS_ERROR = 'GET_GROUP_DETAILS_ERROR',
  FETCH_ERROR = 'FETCH_ERROR',

  // General validation
  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_GROUP_ID = 'INVALID_GROUP_ID',

  // CRUD operations
  CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR',
  CREATION_ERROR = 'CREATION_ERROR',
  UPDATE_GROUP_ERROR = 'UPDATE_GROUP_ERROR',
  UPDATE_ERROR = 'UPDATE_ERROR',
  DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR',
  DELETE_ERROR = 'DELETE_ERROR',

  // Member management
  ADD_MERCHANTS_TO_GROUP_ERROR = 'ADD_MERCHANTS_TO_GROUP_ERROR',
  MEMBER_ADD_ERROR = 'MEMBER_ADD_ERROR',
  REMOVE_MEMBER_ERROR = 'REMOVE_MEMBER_ERROR',
  MEMBER_REMOVE_ERROR = 'MEMBER_REMOVE_ERROR',

  // Template source management
  SET_TEMPLATE_SOURCE_ERROR = 'SET_TEMPLATE_SOURCE_ERROR',
  TEMPLATE_SOURCE_ERROR = 'TEMPLATE_SOURCE_ERROR',

  // Combined errors
  GROUP_OR_MEMBER_NOT_FOUND = 'GROUP_OR_MEMBER_NOT_FOUND',

  // Additional business rules
  GROUP_NAME_EXISTS = 'GROUP_NAME_EXISTS',
  INVALID_SOURCE_MERCHANT = 'INVALID_SOURCE_MERCHANT',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS',
  CANNOT_REMOVE_SOURCE = 'CANNOT_REMOVE_SOURCE',
  GROUP_HAS_MEMBERS = 'GROUP_HAS_MEMBERS',
  INVALID_MERCHANT_ID = 'INVALID_MERCHANT_ID',

  // Group creation specific
  GROUP_CREATION_PARTIAL_FAILURE = 'GROUP_CREATION_PARTIAL_FAILURE',
  INSUFFICIENT_MEMBERS = 'INSUFFICIENT_MEMBERS',
  SOURCE_MERCHANT_NOT_IN_MEMBERS = 'SOURCE_MERCHANT_NOT_IN_MEMBERS',
}
